name: Update Fonts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Setup Typst
        uses: typst-community/setup-typst@v4
      - name: Install dependencies
        working-directory: fonts_downloader
        run: dart pub get
      - name: Run the downloader
        working-directory: fonts_downloader
        run: dart run fonts_downloader.dart
      - name: Setup git credentials for the GitHub Actions Bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config core.quotepath off  # For rendering non-ASCII characters nicely in the upcoming git status
      - name: Show git changes
        run: git status
      - name: Git commit and push
        run: |
          [[ $(git diff-index HEAD --) ]] || { echo "No updates found. No push necessary."; exit 0; }
          git commit -am "Updated fonts"
          git push
